name: Test Workflow

on:
  push:
    branches:
    - task/#17_cicodecoverage

jobs:
  build:
    name: "Test Workflow"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Restore Nuget Packages
      run: dotnet restore EstateManagement.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json

    - name: Build Code
      run: dotnet build EstateManagement.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "EstateManagement.BusinessLogic.Tests\EstateManagement.BusinessLogic.Tests.csproj" --settings "EstateManagement.BusinessLogic.Tests\coverletArgs.runsettings"
        dotnet test "EstateManagement.EstateAggregate.Tests\EstateManagement.EstateAggregate.Tests.csproj" --settings "EstateManagement.EstateAggregate.Tests\coverletArgs.runsettings"
        dotnet test "EstateManagement.Tests\EstateManagement.Tests.csproj" --collect:"XPlat Code Coverage" --settings "EstateManagement.Tests\coverletArgs.runsettings"
        
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1.0.3
      with:
          token: 1e3c769b-a5db-4322-8428-09395a807bd2 #required          
